pipeline {
    agent any
    post {
    failure {
        updateGitlabCommitStatus name: 'build', state: 'failed'
        }
    success {
        updateGitlabCommitStatus name: 'build', state: 'success'
        }
    }
    options {
        gitLabConnection('Ta-Da')
    }
    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType:'All')
    }
    environment {
        repository = "jaehui327/tada-back"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        imagename = "tada-back"
    }
    stages {
        stage('Running') {
            steps {
                updateGitlabCommitStatus name: 'build', state: 'running'
            }
        }
        stage('Clone Repository') {
            steps {
                echo "Clonning Repository"
                git url: 'https://lab.ssafy.com/s08-final/S08P31A503.git',
                branch: 'dev-back',
                 credentialsId: '95086913-a1b2-4c08-8a34-382f19454773'
            }
            post {
                success {
                    echo 'Successfully Cloned Repository'
                }
                failure {
                    error '[Error] Clone Repository'
                }
            }
        }
        stage('Build Gradle') {
            steps {
                dir ('backend/tada') {
                    echo 'Build Gradle'
                    sh 'pwd'
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
                }
            }
            post {
                failure {
                    error '[Error] Build Gradle'
                }
            }
        }
        stage('Build Docker') {
            steps {
                dir ('backend/tada') {
                    echo 'Build Docker'
                    script {
                        dockerImage = docker.build repository + ":latest" 
                    }
                }
            }
            post {
                failure {
                    error '[Error] Build Docker'
                }
            }
        }
        stage('Upload Dockerhub') {
            steps {
                dir ('backend/tada') {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                    sh 'docker push $repository:latest'
                    sh 'docker rmi $repository:latest'
                }
            }
        }
        stage('Connect SSH') {
            steps {
                build 'tada-back-2'
            }
        }
    }
}

