pipeline {
    agent any
    post {
    failure {
        updateGitlabCommitStatus name: 'build', state: 'failed'
        }
    success {
        updateGitlabCommitStatus name: 'build', state: 'success'
        }
    }
    options {
        gitLabConnection('95086913-a1b2-4c08-8a34-382f19454773')
    }
    environment {
        repository = 'jaehui327/tada-back-python'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        imagename = 'tada-back-python'
    }
    stages {
        stage('Running') {
            steps {
                updateGitlabCommitStatus name: 'build', state: 'running'
            }
        }
        stage('Clone Repository') {
            steps {
                echo 'Clonning Repository'
                git url: 'https://lab.ssafy.com/s08-final/S08P31A503.git',
                branch: 'dev-back-python',
                 credentialsId: '95086913-a1b2-4c08-8a34-382f19454773'
            }
            post {
                success {
                    echo 'Successfully Cloned Repository'
                }
                failure {
                    error '[Error] Clone Repository'
                }
            }
        }
        stage('Build Docker') {
            steps {
                dir ('backend/python') {
                    echo 'Build Docker'
                    script {
                        dockerImage = docker.build repository + ":latest" 
                    }
                }
            }
            post {
                failure {
                    error '[Error] Build Docker'
                }
            }
        }
        stage('Upload Dockerhub') {
            steps {
                dir ('backend/python') {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                    sh 'docker push $repository:latest'
                    sh 'docker rmi $repository:latest'
                }
            }
        }
        stage('Connect SSH') {
            steps {
                build 'tada-back-python-2'
            }
        }
    }
}

